### ISSUE TITLE
Not working on Google Sheets

### ISSUE THREAD

**Issue by Loupyboy** [DylanTallchiefGit/xlStudio#1]
Hey! I know it's supposed to be an Excel-only project but is there any plan for Sheets support as well?
It can't be opened so I figured that I'd post that there.

Nice meme DAW btw

**Comment by yellowsink** [comment]
Probably not as it uses VBA Macros, so it has code embedded in it that Google Sheets doesn't understand

**Comment by Loupyboy** [comment]
Oh aight, thanks for the quick response anyway!
