### ISSUE TITLE
URL in README.md is not a link

### ISSUE THREAD

**Issue by bcafuk** [DylanTallchiefGit/xlStudio#2]
The YouTube URL in the readme could be replaced with a link. This can be achieved either using GitHub's automatic linking by adding https:// in front; or by using Markdown syntax to create a link manually, perhaps with custom link text.

**Comment by mmathys** [comment]
Do a PR @bcafuk

**Comment by bcafuk** [comment]
Pull request #3 has been merged, closing issue.

**Comment by DylanTallchiefGit** [comment]
Cheers, much appreciated!
